openapi: 3.0.3
info:
  title: NavigaTUM
  description: |
    Navigating around TUM with excellence – An API to search for rooms,
    buildings and other places

    NavigaTUM is a non-official tool developed by students for students, that aims to help you get around at [TUM](https://tum.de). Feel free to contribute.

    Features:

    - Interactive or RoomFinder-like maps to lookup the position of rooms or buildings
    - Fast and typo-tolerant search
    - Support for different room code formats as well as generic names

    All functionality is also available via an API.

    *Note: Not all buildings in NavigaTUM are owned by TUM, but are instead being used by TUM departments.*
  termsOfService: 'https://nav.tum.sexy/about/privacy'
  contact:
    name: TUM-Dev
    url: 'https://www.tum.app/'
    email: app@tum.de
  license:
    name: GPL v3
    url: 'https://www.gnu.org/licenses/'
  version: 1.0.0
servers:
  - url: 'https://nav.tum.sexy'
    description: https
  - url: 'http://nav.tum.sexy'
    description: http
paths:
  '/api/search':
    get:
      operationId: search
      summary: Search entries
      description: |
        This endpoint is designed to support search-as-you-type results.

        Instead of simply returning a list, the search results are returned in a way to provide a richer experience by splitting them up into sections. You might not necessarily need to implement all types of sections, or all sections features (if you just want to show a list). The order of sections is a suggested order to display them, but you may change this as you like.

        Some fields support highlighting the query terms and it uses DC3 (\x19 or \u{0019}) and DC1 (\x17 or \u{0017}) to mark the beginning/end of a highlighted sequence (See [Wikipedia](https://en.wikipedia.org/wiki/C0_and_C1_control_codes#Modified_C0_control_code_sets)). Some text-renderers will ignore them, but in case you do not want to use them, you might want to remove them from the responses (there is no query parameter for this yet).
      parameters:
        - name: q
          in: query
          description: |
            string you want to search for.
            Note, that the amounts returned can be controlled using the limit\* paramerters.
          required: true
          schema:
            type: string
          examples:
            '5304':
              summary: A 'misspelled' (according to tumonline) lecture-hall
              value: mi hs1
            garching:
              summary: A misspelled campus
              value: sfarching
            fsmpi:
              summary: A regular room
              value: 5606.EG.036
            interims:
              summary: Lecture halls
              value: interims
            sv:
              summary: "'common' names"
              value: AStA
            none:
              summary: All rooms
              value: ''
        - name: limit_buildings
          in: query
          description: |
            Maximum number of buildings/sites to return.  
            Clamped to 0..1000. If this is an problem for you, please open an issue.
          schema:
            type: integer
            default: 5
            maximum: 1000
            minimum: 0
        - name: limit_rooms
          in: query
          description: |
            Maximum number of rooms to return.  
            Clamped to 0..1000. If this is an problem for you, please open an issue.
          schema:
            type: integer
            default: 10
            maximum: 1000
            minimum: 0
        - name: limit_all
          in: query
          description: |
            Overall maximum number of results. Only visible results are counted (i.e. hidden buildings are not counted).  
            Clamped to 1..1000. If this is an problem for you, please open an issue.
          schema:
            type: integer
            default: 10
            maximum: 1000
            minimum: 1
      responses:
        '200':
          description: The search-result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
              examples:
                mw:
                  value:
                    sections:
                      - facet: sites_buildings
                        entries:
                          - id: mw
                            type: joined_building
                            name: "Maschinenwesen (\x19MW\x17)"
                            subtext: Gebäudekomplex
                          - id: '5538'
                            type: building
                            name: "Interims-Tentomax Garching \x19MW\x17, HS1/HS2"
                            subtext: Gebäude
                          - id: '5501'
                            type: building
                            name: 'Gebäudeteil 1, Institut für Mechatronik'
                            subtext: Gebäudeteil
                          - id: '5502'
                            type: building
                            name: 'Gebäudeteil 2, Institut für Werkstoffe und Verarbeitung'
                            subtext: Gebäudeteil
                          - id: '5503'
                            type: building
                            name: 'Gebäudeteil 3, Institut für Produktionstechnik'
                            subtext: Gebäudeteil
                        n_visible: 5
                        estimatedTotalHits: 20
                      - facet: rooms
                        entries:
                          - id: 5510.03.002
                            type: room
                            name: "5510.03.002 (\x19MW\x17 2001, Empore)"
                            subtext: Maschinenwesen (MW)
                            subtext_bold: 3002@5510
                          - id: 5510.01.004A
                            type: room
                            name: "5510.01.004A (Exp.-Bühne zu Hörsaal \x19MW\x17 2001)"
                            subtext: Maschinenwesen (MW)
                            subtext_bold: 1004a@5510
                          - id: 5502.01.250
                            type: room
                            name: 5502.01.250 (Hörsaal)
                            subtext: Maschinenwesen (MW)
                            subtext_bold: 1250@5502
                          - id: 5502.EG.250
                            type: room
                            name: 5502.EG.250 (Ludwig-Prandtl-Hörsaal)
                            subtext: Maschinenwesen (MW)
                            subtext_bold: 0250@5502
                          - id: 5503.EG.350
                            type: room
                            name: 5503.EG.350 (Egbert-von-Hoyer-Hörsaal)
                            subtext: Maschinenwesen (MW)
                            subtext_bold: 0350@5503
                        estimatedTotalHits: 3655
                    time_ms: 16
                nothing:
                  value:
                    sections:
                      - facet: sites_buildings
                        entries: []
                        estimatedTotalHits: 0
                      - facet: rooms
                        entries: []
                        estimatedTotalHits: 0
                    time_ms: 6
                interims-2:
                  value:
                    sections:
                      - facet: sites_buildings
                        entries:
                          - id: '5416'
                            type: building
                            name: "\x19Interims\x17hörsäle II, Jürgen Manchot-Hörsaalgebäude"
                            subtext: Gebäude
                        n_visible: 1
                        estimatedTotalHits: 1
                      - facet: rooms
                        entries:
                          - id: 5416.01.004
                            type: room
                            name: "5416.01.004 (Hörsaal 1 \"\x19Interims\x17 II\")"
                            subtext: 'Interimshörsäle II, Jürgen Manchot-Hörsaalgebäude'
                            subtext_bold: 004@5416
                          - id: 5416.01.003
                            type: room
                            name: "5416.01.003 (Hörsaal \x192\x17, \"\x19Interims\x17 II\")"
                            subtext: 'Interimshörsäle II, Jürgen Manchot-Hörsaalgebäude'
                            subtext_bold: 003@5416
                          - id: 5620.01.102
                            type: room
                            name: "56\x192\x170.01.10\x192\x17 (Hörsaal \x192\x17, \"\x19Interims\x17 I\")"
                            subtext: Interims-Audimax I
                            subtext_bold: "10\x192\x17@56\x192\x170"
                          - id: 0598.EG.001
                            type: room
                            name: 0598.EG.001 (Tentomax HS Stammgelände)
                            subtext: Tentomax Stammgelände (Interims HS)
                            subtext_bold: 0.001@0598
                          - id: 5416.EG.010
                            type: room
                            name: 5416.EG.010 (IT/Audio)
                            subtext: 'Interimshörsäle II, Jürgen Manchot-Hörsaalgebäude'
                            subtext_bold: 010@5416
                        estimatedTotalHits: 23
                    time_ms: 23
        '400':
          description: Invalid Request
          content: {}
        '404':
          description: '`search_query` is empty. Since searching for nothing is nonsensical, we dont support this.'
          content:
            text/plain:
              schema:
                type: string
                enum:
                  - Not found
                example: Not found
        '414':
          description: The uri you are trying to request is unreasonably long. Search querys dont have thousands of chars..
          content: {}
      tags:
        - core
  '/api/get/{id}':
    get:
      operationId: get
      summary: Get entry-details
      description: |
        This returns the full data available for the entry (room/building).

        This is more data, that should be supplied once a user clicks on an entry.
        Preloading this is not an issue on our end, but keep in mind bandwith constraints on your side. The data can be up to 50kB (using gzip) or 200kB unzipped
        The exact data format is specified in the NavigaTUM-data documentation
      parameters:
        - name: id
          in: path
          description: string you want to search for
          required: true
          schema:
            type: string
          examples:
            root:
              summary: The root entry of the NavigaTUM-data
              value: root
            '5304':
              summary: A normal building
              value: '5304'
            garching:
              summary: The garching campus
              value: garching
            mri:
              summary: The MRI campus
              value: garching
            mi:
              summary: 'A large, (custom named) building'
              value: mi
            mw:
              summary: 'An other large, (custom named) building'
              value: mw
            fsmpi:
              summary: A regular room
              value: 5606.EG.036
            rechnerhalle:
              summary: A room with custom props added
              value: 5605.EG.011
            tb-chemie:
              summary: A virtual room
              value: 5401.01.100A
            humangenetik:
              summary: A virtual room
              value: 1543
      responses:
        '200':
          description: More data about the requested building/room
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/RootResponse'
                  - $ref: '#/components/schemas/DetailsResponse'
                discriminator:
                  propertyName: type
                  mapping:
                    root: RootResponse
                    room: DetailsResponse
                    building: DetailsResponse
                    joined_building: DetailsResponse
                    area: DetailsResponse
                    site: DetailsResponse
                    campus: DetailsResponse
              examples:
                mi-hs-1:
                  value:
                    coords:
                      lat: 48.26244490906312
                      lon: 11.669122601167174
                      source: roomfinder
                      utm:
                        easting: 698084.5345
                        northing: 5348914.6199
                        zone_letter: U
                        zone_number: 32
                    id: 5602.EG.001
                    maps:
                      default: interactive
                      roomfinder:
                        available:
                          - height: 487
                            id: rf87
                            name: FMI Garching BT02 EG
                            path: webp/rf87.webp
                            scale: '500'
                            source: Roomfinder
                            width: 399
                            x: 234
                            'y': 286
                          - height: 461
                            id: rf142
                            name: FMI Übersicht
                            path: webp/rf142.webp
                            scale: '2000'
                            source: Roomfinder
                            width: 639
                            x: 499
                            'y': 189
                          - height: 480
                            id: rf80
                            name: Lageplan Campus Garching
                            path: webp/rf80.webp
                            scale: '10000'
                            source: Roomfinder
                            width: 676
                            x: 340
                            'y': 334
                          - height: 603
                            id: rf54
                            name: München
                            path: webp/rf54.webp
                            scale: '200000'
                            source: Roomfinder
                            width: 640
                            x: 444
                            'y': 35
                          - height: 515
                            id: rf156
                            name: München und Umgebung
                            path: webp/rf156.webp
                            scale: '400000'
                            source: Roomfinder
                            width: 420
                            x: 265
                            'y': 167
                        default: rf142
                    name: '5602.EG.001 (MI HS 1, Friedrich L. Bauer Hörsaal)'
                    parent_names:
                      - Standorte
                      - Garching Forschungszentrum
                      - Fakultät Mathematik & Informatik (FMI oder MI)
                      - Hörsaal 1 (BT02)
                    parents:
                      - root
                      - garching
                      - mi
                      - '5602'
                    props:
                      computed:
                        - name: Raumkennung
                          text: 5602.EG.001
                        - name: Architekten-Name
                          text: 00.02.001
                        - name: Adresse
                          text: 'Boltzmannstr. 3, EG, 85748 Garching b. München'
                        - name: Sitzplätze
                          text: '522'
                    ranking_factors:
                      rank_combined: 900
                      rank_type: 100
                      rank_usage: 900
                    sources:
                      base:
                        - name: TUMonline
                          url: 'https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/wbRaum.editRaum?pRaumNr=12325'
                        - name: Roomfinder
                          url: 'https://portal.mytum.de/displayRoomMap?roomid=00.02.001@5602&disable_decoration=yes'
                    type: room
                    type_common_name: Hörsaal
                    usage:
                      din_277: NF5.1
                      din_277_desc: Unterrichtsräume mit festem Gestühl
                      name: Hörsaal
                5606.EG.036:
                  value:
                    coords:
                      lat: 48.26217845031176
                      lon: 11.6686932781057
                      source: roomfinder
                      utm:
                        easting: 698053.7056
                        northing: 5348883.8982
                        zone_letter: U
                        zone_number: 32
                    id: 5606.EG.036
                    maps:
                      default: interactive
                      roomfinder:
                        available:
                          - height: 605
                            id: rf95
                            name: FMI Garching BT06 EG
                            path: webp/rf95.webp
                            scale: '500'
                            source: Roomfinder
                            width: 318
                            x: 207
                            'y': 217
                          - height: 461
                            id: rf142
                            name: FMI Übersicht
                            path: webp/rf142.webp
                            scale: '2000'
                            source: Roomfinder
                            width: 639
                            x: 443
                            'y': 242
                          - height: 480
                            id: rf80
                            name: Lageplan Campus Garching
                            path: webp/rf80.webp
                            scale: '10000'
                            source: Roomfinder
                            width: 676
                            x: 329
                            'y': 344
                          - height: 603
                            id: rf54
                            name: München
                            path: webp/rf54.webp
                            scale: '200000'
                            source: Roomfinder
                            width: 640
                            x: 444
                            'y': 36
                          - height: 515
                            id: rf156
                            name: München und Umgebung
                            path: webp/rf156.webp
                            scale: '400000'
                            source: Roomfinder
                            width: 420
                            x: 265
                            'y': 167
                        default: rf142
                    name: 5606.EG.036 (MPI Fachschaftsbüro im MI)
                    parent_names:
                      - Standorte
                      - Garching Forschungszentrum
                      - Fakultät Mathematik & Informatik (FMI oder MI)
                      - Finger 06 (BT06)
                    parents:
                      - root
                      - garching
                      - mi
                      - '5606'
                    props:
                      computed:
                        - name: Raumkennung
                          text: 5606.EG.036
                        - name: Architekten-Name
                          text: 00.06.036
                        - name: Adresse
                          text: 'Boltzmannstr. 3, EG, 85748 Garching b. München'
                    ranking_factors:
                      rank_combined: 100
                      rank_type: 100
                      rank_usage: 100
                    sources:
                      base:
                        - name: NavigaTUM
                        - name: TUMonline
                          url: 'https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/wbRaum.editRaum?pRaumNr=55601'
                        - name: Roomfinder
                          url: 'https://portal.mytum.de/displayRoomMap?roomid=00.06.036@5606&disable_decoration=yes'
                    type: room
                    type_common_name: Büro
                    usage:
                      din_277: NF2.1
                      din_277_desc: Büroräume
                      name: Büro
        '404':
          description: Invalid input
          content:
            text/plain:
              schema:
                type: string
                enum:
                  - Not found
                example: Not found
      tags:
        - core
  /api/source_code:
    get:
      operationId: source_code
      summary: Get link to running source-code
      description: |
        This endpoint returns a link to the source-code of the repository at the currently running version.
        This endpoint is not required for modifications (as the license is not AGPL), but strongly encouraged.
      responses:
        '200':
          description: The link to the source-code of the repository at the currently running version
          content:
            text/plain:
              schema:
                type: string
                example: 'https://github.com/TUM-Dev/navigatum/tree/eb10c1f4cfbbd66d37f2f9e5e13139c1fde15a4b'
      tags:
        - core
  /api/feedback/get_token:
    post:
      operationId: get_token
      summary: Get a feedback-token
      description: |
        ***Do not abuse this endpoint.***

        This returns a token usable for submitting feedback.
        You should request a token, ***if (and only if) a user is on a feedback page***

        As a rudimentary way of rate-limiting feedback, this endpoint returns a token.
        To post feedback, you will need this token.

        Tokens gain validity after 10s, and are invalid after 12h of being issued.
        They are not refreshable, and are only valid for one usage.

        Global Rate-Limiting:
         - hourly: 20 tokens per hour
         - daily: 50 tokens per
      responses:
        '201':
          description: Returns a usable token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '429':
          description: |
            Too many requests.  
            We are rate-limiting everyone''s requests, please try again later.
          content: {}
        '503':
          description: |
            Service unavailable.  
            We have not configured a GitHub Access Token.  
            This could be because we are experiencing technical difficulties or intentional. Please try again later.
          content: {}
      tags:
        - feedback
  /api/feedback/feedback:
    post:
      operationId: feedback
      summary: Post feedback
      description: |
        ***Do not abuse this endpoint.***

        This posts the actual feedback to github and returns the github link.
        For this Endpoint to work, you need to generate a token via the `/api/feedback/get_token` endpoint.

        ***Important Note:*** Tokens are only used if we return a 201 Created response. Otherwise, they are still valid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      responses:
        '201':
          description: |
            The feedback has been successfully posted to GitHub.
            We return the link to the GitHub issue.
          content:
            text/plain:
              schema:
                type: string
                example: 'https://github.com/TUM-Dev/navigatum/issues/9'
        '400':
          description: If not all fields in the body are present as defined above
          content: {}
        '403':
          description: |
            Forbidden. Causes are (delivered via the body):

              - `Invalid token`: You have not supplied a token generated via the `gen_token`-Endpoint.
              - `Token not old enough, please wait`: Tokens are only valid after 10s.
              - `Token expired`: Tokens are only valid for 12h.
              - `Token already used`: Tokens are non reusable/refreshable single-use items.
          content:
            text/plain:
              schema:
                type: string
                enum:
                  - Invalid token
                  - Token not old enough, please wait
                  - Token expired
                  - Token already used
        '422':
          description: |
            Unprocessable Entity
            Subject or body missing or too short.
          content: {}
        '451':
          description: |
            Unavailable for legal reasons.
            Using this endpoint without accepting the privacy policy is not allowed.
            For us to post to GitHub, this has to be true
          content: {}
        '500':
          description: |
            Internal Server Error.  
            We have a problem communicating with GitHubs servers. Please try again later.
          content: {}
        '503':
          description: |
            Service unavailable.  
            We have not configured a GitHub Access Token.  
            This could be because we are experiencing technical difficulties or intentional. Please try again later.
          content: {}
      tags:
        - feedback
  '/cdn/{size}/{id}_{counter}.webp':
    get:
      operationId: img_cdn
      summary: Get title images
      description: |
        This endpoint is designed to fetch the images, that are described by the `/api/get/{id}`-endpoint.
        You HAVE to get the proper attribution from that endpoint and use it.
      parameters:
        - name: size
          in: path
          description: |
            size of the resource you want

            | name   | default                                                               |
            |--------|-----------------------------------------------------------------------|
            | lg     | max 4k, aspect ratio untouched                                        |
            | md     | max 1920px, aspect ratio untouched                                    |
            | sm     | max 1024px, aspect ratio untouched                                    |
            | thumb  | 256x256, cropped to fit. Usually a center-crop, but sometimes offset. |
            | header | 512x210, cropped to fit. Usually a center-crop, but sometimes offset. |
          required: true
          schema:
            type: string
            enum:
              - lg
              - md
              - sm
              - thumb
              - header
        - name: id
          in: path
          description: id of the recource you want an image for
          required: true
          schema:
            type: string
          examples:
            '5304':
              summary: A normal building
              value: '5304'
            garching:
              summary: A campus
              value: garching
            mi:
              summary: 'A large, (custom named) building'
              value: mi
            fsmpi:
              summary: A regular room
              value: 5606.EG.036
        - name: counter
          in: path
          description: counter of the image you want.
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
          example: 0
      responses:
        '200':
          description: The image you requested
          content:
            image/webp:
              schema:
                type: string
                format: binary
              example: 'https://nav.tum.sexy/cdn/thumb/mi_0.webp'
        '400':
          description: |
            Bad Request.    
            The request was malformed.  
            Please check your request and try again.
          content: {}
        '404':
          description: Requested Resource Not Found
          content:
            text/plain:
              schema:
                type: string
                enum:
                  - Not found
                example: Not found
        '414':
          description: 'The uri you are trying to request is unreasonably long. neither ids, nor any other parameter has more than 30 chars..'
          content: {}
      tags:
        - cdn
  '/cdn/maps/{source}/{id}.webp':
    get:
      operationId: maps_cdn
      summary: Get title images
      description: |
        This endpoint is designed to fetch the images, that are described by the `/api/get/{id}`-endpoint.
        You HAVE to get the proper attribution from that endpoint and use it.
      parameters:
        - name: source
          in: path
          description: source of the resource you want
          required: true
          schema:
            type: string
            enum:
              - overlay
              - roomfinder
        - name: id
          in: path
          description: id of the map you want
          required: true
          schema:
            type: string
            minLength: 1
          examples:
            rf142:
              summary: MI main overview (roomfinder only)
              value: rf142
            mi_0:
              summary: MI main overview (overlay only)
              value: mi_0
            garching:
              summary: StudiTUM Garching (roomfinder + overview)
              value: '5532_2'
      responses:
        '200':
          description: The map you requested
          content:
            image/webp:
              schema:
                type: string
                format: binary
              example: 'https://nav.tum.sexy/cdn/maps/roomfinder/rf142.webp'
        '400':
          description: |
            Bad Request.    
            The request was malformed.  
            Please check your request and try again.
          content: {}
        '404':
          description: Requested Resource Not Found
          content:
            text/plain:
              schema:
                type: string
                enum:
                  - Not found
                example: Not found
        '414':
          description: 'The uri you are trying to request is unreasonably long. neither ids, nor any other parameter has more than 30 chars..'
          content: {}
      tags:
        - cdn
  /api/health:
    get:
      operationId: api-health
      summary: API healthcheck
      description: |
        If this endpoint does not return 200, the API is experiencing a catastrophic outage. Should never happen.
      responses:
        '200':
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                enum:
                  - healthy
        '503':
          description: Service Unavailable
          content: {}
      tags:
        - health
  /cdn/health:
    get:
      operationId: cdn-health
      summary: CDN healthcheck
      description: |
        If this endpoint does not return 200, the CDN is experiencing a catastrophic outage. Should never happen.
      responses:
        '200':
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                enum:
                  - healthy
        '503':
          description: Service Unavailable
          content: {}
      tags:
        - health
  /health:
    get:
      operationId: web-health
      summary: Website healthcheck
      description: |
        If this endpoint does not return 200, the Website is experiencing a catastrophic outage. Should never happen.
      responses:
        '200':
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                enum:
                  - healthy
        '503':
          description: Service Unavailable
          content: {}
      tags:
        - health
components:
  schemas:
    Props:
      description: Data for the info-card table
      type: object
      properties:
        computed:
          type: array
          items:
            $ref: '#/components/schemas/Prop'
      required:
        - computed
    Prop:
      type: object
      properties:
        name:
          type: string
          example: Raumkennung
        text:
          type: string
          example: 5602.EG.001
      required:
        - name
        - text
    ImageInfo:
      description: 'The information you need to request Images from the /cdn/{size}/{id}_{counter}.webp endpoint'
      type: object
      properties:
        name:
          description: 'The name of the image file. consists of {building_id}_{image_id}.webp, where image_id is a counter starting at 0'
          type: string
          example: mi_0.webp
        author:
          $ref: '#/components/schemas/PossibleURLRef'
        source:
          $ref: '#/components/schemas/PossibleURLRef'
        license:
          $ref: '#/components/schemas/PossibleURLRef'
        meta:
          $ref: '#/components/schemas/ImageMetadata'
        sections:
          discriminator:
            propertyName: facet
            mapping:
              sites_buildings: SitesBuildings
              rooms: Rooms
          oneOf:
            - $ref: '#/components/schemas/SitesBuildings'
            - $ref: '#/components/schemas/Rooms'
      required:
        - name
        - author
        - source
        - license
    ImageMetadata:
      description: |
        Aditional data about the images. Does not have to be displayed.
        All fields are optional.
      type: object
      properties:
        date:
          description: optional date description
          type: string
        location:
          description: optional location description
          type: string
        geo:
          description: 'optional coordinates in lat,lon'
          type: string
        image_url:
          description: |
            optional in contrast to source this points to the image itself.
            You should not use this to request the images, as they are not scaled.
          type: string
        caption:
          description: optional caption
          type: string
        headline:
          description: optional headline
          type: string
        event:
          description: optional the event this image was taken at
          type: string
        faculty:
          description: optional the event this image is about
          type: string
        building:
          description: optional the building this image is about
          type: string
        department:
          description: optional the department this image is about
          type: string
    PossibleURLRef:
      description: 'Additional information you should include, if you decide to display the image for legal and attribution reasons'
      type: object
      properties:
        text:
          description: 'The text to display'
          type: string
        url:
          description: 'The URL to the referenced information. Always either null or a valid URL'
          nullable: true
          type: string
          pattern: .+
      required:
        - text
    Coordinate:
      type: object
      properties:
        lat:
          description: The latitude
          type: number
          format: double
          example: 48.26244490906312
          maximum: 90
          minimum: -90
        lon:
          description: The latitude
          type: number
          format: double
          example: 48.26244490906312
          maximum: 180
          minimum: -180
        source:
          description: The source of the Coordinates
          type: string
          example: roomfinder
        utm:
          type: object
          properties:
            easting:
              description: The easting
              type: number
              format: double
              example: 698288.4681410069
            northing:
              description: The northing
              type: number
              format: double
              example: 5349538.736274569
            zone:
              description: The zone
              type: string
              example: U
              pattern: '[C-HJ-NP-X]'
            zone_number:
              description: The zone number
              type: integer
              format: int32
              example: 32
              maximum: 60
              minimum: 1
      required:
        - lat
        - lon
        - source
    Maps:
      type: object
      properties:
        default:
          description: The type of the Map that should be shown by default
          type: string
          example: interactive
          enum:
            - interactive
            - roomfinder
        roomfinder:
          $ref: '#/components/schemas/RoomfinderMap'
        overlays:
          description: |
            null would mean no overlay maps are displayed by default.
            For rooms you should add a warning that no floor map is available for this room
          allOf:
            - nullable: true
            - $ref: '#/components/schemas/OverlayMap'
      required:
        - default
    RoomfinderMap:
      type: object
      properties:
        default:
          description: 'The id of the map, that should be shown as a default'
          type: string
          example: rf142
        available:
          type: array
          items:
            $ref: '#/components/schemas/RoomfinderMapEntry'
      required:
        - default
        - available
    RoomfinderMapEntry:
      type: object
      properties:
        name:
          description: The human-readable name of the map
          type: string
          example: FMI Übersicht
        id:
          description: The machine-readable name of the map
          type: string
          example: rf142
        scale:
          description: 'Scale of the map. 2000 means 1:2000.'
          type: string
          example: '2000'
          pattern: '[0-9]+'
        height:
          description: Map image x dimensions
          type: integer
          format: int32
          example: 461
          minimum: 0
        width:
          description: Map image y dimensions
          type: integer
          format: int32
          example: 639
          minimum: 0
        x:
          description: x Position on map
          type: integer
          format: int32
          example: 499
          minimum: 0
        y:
          description: y Position on map image
          type: integer
          format: int32
          example: 189
          minimum: 0
      required:
        - name
        - id
        - scale
        - height
        - width
        - x
        - y
    OverlayMap:
      type: object
      properties:
        default:
          description: |
            The floor-id of the map, that should be shown as a default.  
            null:
            - We suggest, you dont show a map by default.
            - This is only the case for buildings or other such entities and not for rooms, if we know where they are and a map exists
          type: integer
          example: 0
          nullable: true
        available:
          type: array
          items:
            $ref: '#/components/schemas/OverlayMapEntry'
      required:
        - default
        - available
    OverlayMapEntry:
      type: object
      properties:
        id:
          description: |
            The machine-readable floor-id of the map.  
            Should start with 0 for the ground level (defined by the main entrance) and increase or decrease.
            It is not guaranteed that numbers are consecutive or that `1` corresponds to level `01`, because buildings sometimes have more complicated layouts. They are however always in the correct (physical) order.
          type: integer
          example: 0
        floor:
          description: |
            Floor of the Map.
            Should be used for display to the user in selectors.  
            Matches the floor part of the TUMonline roomcode.
          type: string
          example: 'EG'
        name:
          description: The human-readable name of the map
          type: string
          example: MI Gebäude (EG)
        file:
          description: The filename of the map
          type: string
          example: webp/rf95.webp
        coordinates:
          description: Coordinates are four [lon, lat] pairs, for the top left, top right, bottom right, bottom left image corners.
          type: array
          items:
            type: array
            items:
              type: number
            minItems: 2
            maxItems: 2
          minItems: 4
          maxItems: 4
      required:
        - id
        - floor
        - name
        - file
        - coordinates
    Rooms:
      type: object
      properties:
        facet:
          description: These indicate the type of item this represents
          type: string
          example: rooms
          enum:
            - rooms
        estimatedTotalHits:
          description: The estimated (not exact) number of hits for that query
          type: integer
          format: int64
          minimum: 0
        entries:
          type: array
          items:
            $ref: '#/components/schemas/RoomEntry'
      required:
        - estimatedTotalHits
        - facet
        - entries
    SitesBuildings:
      type: object
      properties:
        facet:
          description: These indicate the type of item this represents
          type: string
          example: sites_buildings
          enum:
            - sites_buildings
        estimatedTotalHits:
          description: The estimated (not exact) number of hits for that query
          type: integer
          format: int64
          minimum: 0
        entries:
          type: array
          items:
            $ref: '#/components/schemas/SitesBuildingsEntry'
        n_visible:
          description: |
            A recommendation how many of the entries should be displayed by default.  
            The number is usually from 0-5.  
            More results might be displayed when clicking "expand".  
            If this field is not present, then all entries are displayed.
          type: integer
          format: int64
          minimum: 0
      required:
        - estimatedTotalHits
        - facet
        - entries
    RoomEntry:
      allOf:
        - $ref: '#/components/schemas/SitesBuildingsEntry'
        - type: object
          required:
            - subtext_bold
          properties:
            subtext_bold:
              description: 'Subtext to show below the search (by default in bold and after the non-bold subtext). Usually contains the arch-id of the room, which is another common room id format, and supports highlighting.'
              type: string
            parsed_id:
              description: 'This is an optional feature, that is only supported for some rooms. It might be displayed instead or before the name, to show that a different room id format has matched, that was probably used. See the image below for an example. It will be cropped to a maximum length to not take too much space in UIs. Supports highlighting.'
              type: string
    SitesBuildingsEntry:
      type: object
      properties:
        id:
          description: The id of the room
          type: string
        type:
          description: the type of the room/site/building
          type: string
        name:
          description: Subtext to show below the search result. Usually contains the context of where this rooms is located in. Currently not highlighted.
          type: string
        subtext:
          description: Subtext to show below the search result. Usually contains the context of where this rooms is located in. Currently not highlighted.
          type: string
      required:
        - id
        - type
        - name
        - subtext
    TokenResponse:
      type: object
      properties:
        token:
          description: 'The token, that can be used to generate feedback'
          type: string
          example: '999999999999999'
          maxLength: 15
          minLength: 15
          pattern: '[0-9]+'
      required:
        - token
      x-examples:
        token:
          token: '999999999999999'
    SearchResponse:
      type: object
      properties:
        sections:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/SitesBuildings'
              - $ref: '#/components/schemas/Rooms'
            discriminator:
              propertyName: facet
              mapping:
                sites_buildings: SitesBuildings
                rooms: Rooms
        time_ms:
          description: |
            Time the search took in the server side, not including network delay
            Maximum as by awc timeout. other timeouts (browser, your client) may be smaller
            Expected average is 10..50 for uncached, regular requests
          type: integer
          format: int32
          example: 42
          maximum: 75000
          minimum: 0
      required:
        - sections
        - time_ms
    DetailsResponse:
      allOf:
        - $ref: '#/components/schemas/BaseDetailsResponse'
        - type: object
          properties:
            id:
              description: 'The id, that was requested'
              type: string
            type:
              description: The type of the entry
              type: string
              enum:
                - room
                - building
                - joined_building
                - area
                - site
                - campus
            coords:
              $ref: '#/components/schemas/Coordinate'
            maps:
              $ref: '#/components/schemas/Maps'
          required:
            - id
            - type
            - coords
            - maps
    RootResponse:
      allOf:
        - $ref: '#/components/schemas/BaseDetailsResponse'
        - type: object
          properties:
            id:
              description: 'The id, that was requested'
              type: string
              enum:
                - root
            type:
              description: The type of the entry
              type: string
              enum:
                - root
          required:
            - id
            - type
    BaseDetailsResponse:
      type: object
      properties:
        type_common_name:
          description: The type of the entry in a human-readable form
          type: string
        name:
          description: The name of the entry in a human-readable form
          type: string
          example: '5602.EG.001 (MI HS 1, Friedrich L. Bauer Hörsaal)'
        parents:
          type: array
          items:
            type: string
            description: The ids of the parents. They are ordered as they would appear in a Breadcrumb menu. See parent_names for their actual ids.
          example:
            - root
            - garching
        parent_names:
          type: array
          items:
            type: string
            description: The ids of the parents. They are ordered as they would appear in a Breadcrumb menu. See parents for their actual ids.
            example:
              - Standorte
              - Garching Forschungszentrum
        props:
          $ref: '#/components/schemas/Props'
        imgs:
          type: array
          items:
            $ref: '#/components/schemas/ImageInfo'
        ranking_factors:
          $ref: '#/components/schemas/RankingFactors'
      required:
        - type_common_name
        - name
        - parents
        - parent_names
        - props
        - ranking_factors
    RankingFactors:
      type: object
      properties:
        rank_combined:
          description: How much the combined ranking is important
          type: integer
          format: int32
        rank_type:
          description: How much the type is important
          type: integer
          format: int32
        rank_usage:
          description: How much the usage is important
          type: integer
          format: int32
        rank_boost:
          description:  |
            Automatic boost or suppression based on entry properties:
            - numbers of buildings for a `campus`/`area`/`site`,
            - numbers of seats for a `room`,
            - number of regular rooms for a `building`/`joined_building`
          type: integer
          format: int32
        rank_custom:
          description: Custom boost or suppression factor defined by us
          type: integer
          format: int32
      required:
        - rank_combined
        - rank_type
        - rank_usage
    TokenRequest:
      type: object
      properties:
        token:
          description: 'The token, that can be used to generate feedback'
          type: string
          example: '999999999999999'
          maxLength: 15
          minLength: 15
          pattern: '[0-9]+'
        category:
          description: | 
            The category of the feedback.  
            Enum attribute is softly enforced: Any value not listed below will be replaced by "other"
          type: string
          example: bug
          enum:
            - general
            - bug
            - feature
            - search
            - entry
            - other
        subject:
          description: The subject/title of the feedback
          type: string
          example: A catchy title
          maxLength: 512
          minLength: 4
        body:
          description: The body/description of the feedback
          type: string
          example: A clear description what happened where and how we should improve it
          maxLength: 1048576
          minLength: 4
        privacy_checked:
          description: |
            Whether the user has checked the privacy-checkbox.
            We are posting the feedback publicly on GitHub (not a EU-Company). You have to also include such a checkmark.
            For inspiration on how to do this, see our website.
          type: boolean
          example: true
        delete_issue_requested:
          description: |
            Whether the user has requested to delete the issue.
            If the user has requested to delete the issue, we will delete it from GitHub after processing it
            If the user has not requested to delete the issue, we will not delete it from GitHub and it will remain as a closed issue.
          type: boolean
          example: true
      required:
        - token
        - category
        - subject
        - body
        - privacy_checked
        - delete_issue_requested
tags:
  - name: core
    description: the API to access/search for room information
  - name: cdn
    description: Images for some of the rooms
  - name: feedback
    description: the API to access/search for room information
  - name: health
    description: 'These endpoints are used to check the health of the API, website and cdn'
externalDocs:
  description: Visit our Github Page for more in-depth documentation
  url: 'https://github.com/TUM-Dev/navigatum'
